/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sameka (https://sketchfab.com/sameka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/virtual-stage-cyberpunk-0e2c915556ae42ffb659b37810133bb5
title: Virtual stage Cyberpunk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/city.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-127.04, -21.03, 3.77]} rotation={[Math.PI / 2, 0, 1.23]} scale={0.08}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.glossy_metal} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.neon_blue} />
          </group>
          <group position={[-106.09, -22.92, -27.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.15}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.neon} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.neon_blue} />
          </group>
          <group position={[-89.39, -21.03, 32.44]} rotation={[Math.PI / 2, 0, 1.04]} scale={0.08}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.glossy_metal} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.neon_blue} />
          </group>
          <group position={[7.87, 0, 0]}>
            <mesh geometry={nodes.Object_30.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_33.geometry} material={materials.metal_imperfecr} />
          </group>
          <group position={[-70.29, -18.94, -37.27]} rotation={[Math.PI / 2, 0, -1.53]} scale={0.35}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.glossy_metal} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_37.geometry} material={materials.neon} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.m2_M} />
            <mesh geometry={nodes.Object_39.geometry} material={materials.vl_M} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_41.geometry} material={materials.metal} />
          </group>
          <group position={[-123.12, -14.83, -25.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
            <mesh geometry={nodes.Object_43.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.neon_orange} />
          </group>
          <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} />
          <group position={[4.86, 5.04, -0.3]} rotation={[1.29, -0.65, -2.01]} scale={0.9}>
            <mesh geometry={nodes.Object_49.geometry} material={materials['neon_orange.001']} />
          </group>
          <group position={[3.75, 5.04, 3.2]} rotation={[1.85, -0.65, -1.13]} scale={0.9}>
            <mesh geometry={nodes.Object_51.geometry} material={materials['neon_orange.001']} />
          </group>
          <group position={[0, 0.7, 0.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.32}>
            <mesh geometry={nodes.Object_53.geometry} material={materials.presenter1} />
          </group>
          <group position={[0, 0.7, -0.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.32}>
            <mesh geometry={nodes.Object_55.geometry} material={materials.presenter2} />
          </group>
          <group position={[-8.26, 4.35, -6.01]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.metal_rig} />
          </group>
          <group position={[-2.66, 1.38, 0]} scale={1.54}>
            <mesh geometry={nodes.Object_62.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.light_metal} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.neon_orange} />
          </group>
          <group position={[-2.29, 1.38, 0]} scale={1.56}>
            <mesh geometry={nodes.Object_66.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_67.geometry} material={materials.neon} />
          </group>
          <group position={[-2.29, 1.38, 0]} scale={1.56}>
            <mesh geometry={nodes.Object_69.geometry} material={materials.bg_led} />
          </group>
          <group position={[1.16, 0, 0]}>
            <mesh geometry={nodes.Object_71.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_72.geometry} material={materials.neon_blue} />
          </group>
          <group position={[-8.26, 4.35, 6.16]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_75.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_76.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_77.geometry} material={materials.metal_rig} />
          </group>
          <group position={[-17.89, 4.35, -6.01]}>
            <mesh geometry={nodes.Object_79.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_81.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_82.geometry} material={materials.metal_rig} />
          </group>
          <group position={[-17.89, 4.35, 6.16]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Object_84.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_85.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_86.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_87.geometry} material={materials.metal_rig} />
          </group>
          <group position={[-38.48, 4.35, -6.01]}>
            <mesh geometry={nodes.Object_89.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_90.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_91.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_92.geometry} material={materials.metal_rig} />
          </group>
          <group position={[-38.48, 4.35, 6.16]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_95.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_96.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_97.geometry} material={materials.metal_rig} />
          </group>
          <group position={[0, -0.67, 0]}>
            <mesh geometry={nodes.Object_99.geometry} material={materials.metal_imperfecr} />
            <mesh geometry={nodes.Object_100.geometry} material={materials.neon} />
            <mesh geometry={nodes.Object_101.geometry} material={materials.glossy_metal} />
            <mesh geometry={nodes.Object_102.geometry} material={materials.metal_rig} />
            <mesh geometry={nodes.Object_103.geometry} material={materials.circuit} />
          </group>
          <group position={[0, 6.01, 0]}>
            <mesh geometry={nodes.Object_105.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_106.geometry} material={materials.neon_blue} />
          </group>
          <group position={[0, 5.01, 0]}>
            <mesh geometry={nodes.Object_108.geometry} material={materials.circuit_blue} />
            <mesh geometry={nodes.Object_109.geometry} material={materials.neon_blue} />
          </group>
          <group position={[0, 5.41, 0]} scale={[0.35, 1, 0.35]}>
            <mesh geometry={nodes.Object_111.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_112.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_113.geometry} material={materials.neon} />
          </group>
          <group position={[2.37, 5.4, -0.86]} rotation={[0, Math.PI / 9, -Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_115.geometry} material={materials.metal} />
          </group>
          <group position={[-2.41, 5.4, 0.88]} rotation={[0, Math.PI / 9, -Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_117.geometry} material={materials.metal} />
          </group>
          <group position={[1.05, 5.4, -2.29]} rotation={[0, 1.13, -Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_119.geometry} material={materials.metal} />
          </group>
          <group position={[-1.09, 5.4, 2.31]} rotation={[0, 1.13, -Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_121.geometry} material={materials.metal} />
          </group>
          <group position={[-0.89, 5.4, -2.38]} rotation={[-Math.PI, 1.22, Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_123.geometry} material={materials.metal} />
          </group>
          <group position={[0.85, 5.4, 2.39]} rotation={[-Math.PI, 1.22, Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_125.geometry} material={materials.metal} />
          </group>
          <group position={[-2.32, 5.4, -1.07]} rotation={[-Math.PI, 0.44, Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_127.geometry} material={materials.metal} />
          </group>
          <group position={[2.28, 5.4, 1.08]} rotation={[-Math.PI, 0.44, Math.PI / 2]} scale={[0.14, 0.86, 0.14]}>
            <mesh geometry={nodes.Object_129.geometry} material={materials.metal} />
          </group>
          <group position={[0, 5.41, 0]} scale={[0.76, 1, 0.76]}>
            <mesh geometry={nodes.Object_131.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.neon} />
          </group>
          <group position={[0, -1.89, 0]} scale={4.23}>
            <mesh geometry={nodes.Object_134.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_135.geometry} material={materials.neon_blue} />
            <mesh geometry={nodes.Object_136.geometry} material={materials.neon_orange} />
            <mesh geometry={nodes.Object_137.geometry} material={materials.circuit} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/city.gltf')
