/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Oleaf (https://sketchfab.com/homkahom0)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/my-room-109790fce06a4ff3b4b96c2c2cfcc33e
title: My room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/my_room.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.comp_blinn1_0.geometry} material={nodes.comp_blinn1_0.material} />
          <mesh geometry={nodes.triangle_blinn1_0.geometry} material={nodes.triangle_blinn1_0.material} />
          <mesh geometry={nodes.keyboard_blinn1_0.geometry} material={nodes.keyboard_blinn1_0.material} />
          <mesh geometry={nodes.railing_blinn1_0.geometry} material={nodes.railing_blinn1_0.material} />
          <mesh geometry={nodes.table_blinn1_0.geometry} material={nodes.table_blinn1_0.material} />
          <mesh geometry={nodes.cabin_blinn1_0.geometry} material={nodes.cabin_blinn1_0.material} />
          <mesh geometry={nodes.lamp_emis_blinn1_0.geometry} material={nodes.lamp_emis_blinn1_0.material} />
          <mesh geometry={nodes.kovrik_blinn1_0.geometry} material={nodes.kovrik_blinn1_0.material} />
          <mesh geometry={nodes.vac_black_blinn1_0.geometry} material={nodes.vac_black_blinn1_0.material} />
          <mesh geometry={nodes.miuse_blinn1_0.geometry} material={nodes.miuse_blinn1_0.material} />
          <mesh geometry={nodes.red_vac_blinn1_0.geometry} material={nodes.red_vac_blinn1_0.material} />
          <mesh geometry={nodes.vacuum1_blinn1_0.geometry} material={nodes.vacuum1_blinn1_0.material} />
          <mesh geometry={nodes.pCylinder5_blinn1_0.geometry} material={nodes.pCylinder5_blinn1_0.material} />
          <mesh geometry={nodes.stylus_blinn1_0.geometry} material={nodes.stylus_blinn1_0.material} />
          <mesh geometry={nodes.vires_blinn1_0.geometry} material={nodes.vires_blinn1_0.material} />
          <mesh geometry={nodes.tablet_blinn1_0.geometry} material={nodes.tablet_blinn1_0.material} />
          <mesh geometry={nodes.radiator_blinn1_0.geometry} material={nodes.radiator_blinn1_0.material} />
          <mesh geometry={nodes.window_blinn1_0.geometry} material={nodes.window_blinn1_0.material} />
          <mesh geometry={nodes.handls_blinn1_0.geometry} material={nodes.handls_blinn1_0.material} />
          <mesh geometry={nodes.emis_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.vacuumgrey_blinn1_0.geometry} material={nodes.vacuumgrey_blinn1_0.material} />
          <mesh geometry={nodes.red_bttns_blinn1_0.geometry} material={nodes.red_bttns_blinn1_0.material} />
          <mesh geometry={nodes.lamp_white_blinn1_0.geometry} material={nodes.lamp_white_blinn1_0.material} />
          <mesh geometry={nodes.lamp_bl_blinn1_0.geometry} material={nodes.lamp_bl_blinn1_0.material} />
          <mesh geometry={nodes.pillows_blinn1_0.geometry} material={nodes.pillows_blinn1_0.material} />
          <mesh geometry={nodes.polySurface53_blinn1_0.geometry} material={nodes.polySurface53_blinn1_0.material} />
          <mesh geometry={nodes.chair_body_blinn1_0.geometry} material={nodes.chair_body_blinn1_0.material} />
          <mesh geometry={nodes.monitor2_blinn1_0.geometry} material={nodes.monitor2_blinn1_0.material} />
          <mesh geometry={nodes.monitor3_blinn1_0.geometry} material={nodes.monitor3_blinn1_0.material} />
          <mesh geometry={nodes._________6_blinn1_0.geometry} material={nodes._________6_blinn1_0.material} />
          <mesh geometry={nodes.body1_blinn1_0.geometry} material={nodes.body1_blinn1_0.material} />
          <mesh geometry={nodes.window4_phong1_0.geometry} material={materials.phong1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/my_room.gltf')
